// ── Languages ────────────────────────────────────────────
// All three are now available — no locking.
const LANGUAGES = [
  { id: 'pt-PT', flag: '🇵🇹' },
  { id: 'id-ID', flag: '🇮🇩' },
  { id: 'fr-FR', flag: '🇫🇷' },
];

// ── Exercise builders ─────────────────────────────────────
//
// translation: { 'pt-PT': '...', 'id-ID': '...' }
//   — the meaning of the target word in the learner's language
//
// questionType:
//   'word'    → "How do you say '{translation}' in {lang}?"
//               options = target-language words (no translation needed)
//   'meaning' → "What does '{target}' mean?"
//               options = meanings in UI language  (optionsByLang required)
//
// For 'listening' the options are always meanings → optionsByLang required.

const mc = (target, ptTrans, idTrans, options) => ({
  type: 'multiple-choice', questionType: 'word',
  target,
  translation: { 'pt-PT': ptTrans, 'id-ID': idTrans },
  options,
});

const mcM = (target, ptTrans, idTrans, ptOpts, idOpts) => ({
  type: 'multiple-choice', questionType: 'meaning',
  target,
  translation: { 'pt-PT': ptTrans, 'id-ID': idTrans },
  optionsByLang: { 'pt-PT': ptOpts, 'id-ID': idOpts },
});

const mcI = (ptInstruction, idInstruction, options, answerIndex) => ({
  type: 'multiple-choice', questionType: 'instruction',
  instruction: { 'pt-PT': ptInstruction, 'id-ID': idInstruction },
  target: options[answerIndex],
  options,
  translation: {},
});

const ta = (target, ptTrans, idTrans) => ({
  type: 'type-answer',
  target,
  translation: { 'pt-PT': ptTrans, 'id-ID': idTrans },
});

const li = (target, ptTrans, idTrans, ptOpts, idOpts) => ({
  type: 'listening',
  target,
  translation: { 'pt-PT': ptTrans, 'id-ID': idTrans },
  optionsByLang: { 'pt-PT': ptOpts, 'id-ID': idOpts },
});

const sp = (target, ptTrans, idTrans) => ({
  type: 'speaking',
  target,
  translation: { 'pt-PT': ptTrans, 'id-ID': idTrans },
});

const wm = (sentence, answer, wordBank, ptTrans, idTrans) => ({
  type: 'word-match',
  sentence,
  answer,
  wordBank,
  target: answer,
  translation: { 'pt-PT': ptTrans, 'id-ID': idTrans },
});

const tut = (ptInstruction, idInstruction, exampleDesc, target, ptTrans, idTrans) => ({
  type: 'tutorial',
  instruction: { 'pt-PT': ptInstruction, 'id-ID': idInstruction },
  exampleDesc,
  target,
  translation: { 'pt-PT': ptTrans, 'id-ID': idTrans },
});

const tutRead = (ptInstruction, idInstruction, text) => ({
  type: 'tutorial-read',
  instruction: { 'pt-PT': ptInstruction, 'id-ID': idInstruction },
  text,
});

const tf = (sentence, answer, text) => ({
  type: 'true-false',
  sentence,
  answer,  // 'true' | 'false'
  text,
});

// ── Levels ────────────────────────────────────────────────
const LEVELS = {
  'pt-PT': [
    { id: 'ACESSO',   cefr: 'A1' },
    { id: 'CIPLE',   cefr: 'A2' },
    { id: 'DEPLE',   cefr: 'B1' },
    { id: 'DIPLE',   cefr: 'B2' },
    { id: 'DAPLE',   cefr: 'C1' },
    { id: 'DUPLE',   cefr: 'C2' },
  ],
  'id-ID': [
    { id: 'BIPA 1',  cefr: 'A1' },
    { id: 'BIPA 2',  cefr: 'A2' },
    { id: 'BIPA 3',  cefr: 'B1' },
    { id: 'BIPA 4',  cefr: 'B2' },
    { id: 'BIPA 5',  cefr: 'C1' },
    { id: 'BIPA 6',  cefr: 'C2' },
  ],
  'fr-FR': [
    { id: 'DELF A1', cefr: 'A1' },
    { id: 'DELF A2', cefr: 'A2' },
    { id: 'DELF B1', cefr: 'B1' },
    { id: 'DELF B2', cefr: 'B2' },
    { id: 'DALF C1', cefr: 'C1' },
    { id: 'DALF C2', cefr: 'C2' },
  ],
};

// ── Lessons ───────────────────────────────────────────────
const LESSONS = {

  // ── Portuguese ─────────────────────────────
  'pt-PT': {
    'ACESSO': [
    {
      id: 'pt-greetings', title: 'lessonGreetings', subtitle: 'lessonGreetingsSub',
      exercises: [
        mc('Olá',        'Olá',        'Halo',             ['Olá', 'Obrigado', 'Sim', 'Adeus']),
        li('Bom dia',    'Bom dia',    'Selamat pagi',
           ['Bom dia', 'Boa tarde', 'Boa noite', 'Adeus'],
           ['Selamat pagi', 'Selamat sore', 'Selamat malam', 'Selamat tinggal']),
        ta('Obrigado',   'Obrigado',   'Terima kasih'),
        sp('Boa tarde',  'Boa tarde',  'Selamat sore'),
        mcM('Adeus',     'Adeus',      'Selamat tinggal',
           ['Olá', 'Por favor', 'Adeus', 'Sim'],
           ['Halo', 'Tolong', 'Selamat tinggal', 'Ya']),
        li('Boa noite',  'Boa noite',  'Selamat malam',
           ['Bom dia', 'Boa tarde', 'Boa noite', 'Tudo bem?'],
           ['Selamat pagi', 'Selamat sore', 'Selamat malam', 'Apa kabar?']),
        ta('Por favor',  'Por favor',  'Tolong'),
        sp('Com licença','Com licença','Permisi'),
      ],
    },
    {
      id: 'pt-numbers', title: 'lessonNumbers', subtitle: 'lessonNumbersSub',
      exercises: [
        mc('Zero',   'Zero',   'Nol',           ['Zero', 'Onze', 'Treze', 'Vinte']),
        mc('Um',    'Um',    'Satu',    ['Um', 'Dois', 'Três', 'Quatro']),
        li('Dois',  'Dois',  'Dua',
           ['Um', 'Dois', 'Três', 'Quatro'],
           ['Satu', 'Dua', 'Tiga', 'Empat']),
        ta('Três',  'Três',  'Tiga'),
        sp('Quatro','Quatro','Empat'),
        mcM('Cinco','Cinco', 'Lima',
           ['Três', 'Quatro', 'Cinco', 'Seis'],
           ['Tiga', 'Empat', 'Lima', 'Enam']),
        li('Seis',  'Seis',  'Enam',
           ['Quatro', 'Cinco', 'Seis', 'Sete'],
           ['Empat', 'Lima', 'Enam', 'Tujuh']),
        ta('Sete',  'Sete',  'Tujuh'),
        sp('Oito',  'Oito',  'Delapan'),
        mc('Nove',   'Nove',   'Sembilan',      ['Sete', 'Oito', 'Nove', 'Dez']),
        mc('Dez',    'Dez',    'Sepuluh',       ['Oito', 'Nove', 'Dez', 'Onze']),
        mc('Onze',   'Onze',   'Sebelas',       ['Zero', 'Onze', 'Dezoito', 'Vinte']),
        mc('Treze',  'Treze',  'Tiga belas',    ['Onze', 'Treze', 'Dezoito', 'Vinte']),
        mc('Dezoito','Dezoito','Delapan belas', ['Onze', 'Treze', 'Dezoito', 'Vinte']),
        mc('Vinte',  'Vinte',  'Dua puluh',     ['Zero', 'Treze', 'Dezoito', 'Vinte']),
      ],
    },
    {
      id: 'pt-colors', title: 'lessonColors', subtitle: 'lessonColorsSub',
      exercises: [
        mc('Vermelho', 'Vermelho', 'Merah',   ['Vermelho', 'Azul', 'Verde', 'Amarelo']),
        li('Azul',     'Azul',     'Biru',
           ['Vermelho', 'Azul', 'Verde', 'Amarelo'],
           ['Merah', 'Biru', 'Hijau', 'Kuning']),
        ta('Verde',    'Verde',    'Hijau'),
        mcM('Amarelo', 'Amarelo',  'Kuning',
           ['Vermelho', 'Azul', 'Verde', 'Amarelo'],
           ['Merah', 'Biru', 'Hijau', 'Kuning']),
        sp('Branco',   'Branco',   'Putih'),
        mc('Preto',    'Preto',    'Hitam',   ['Preto', 'Branco', 'Castanho', 'Laranja']),
        ta('Castanho', 'Castanho', 'Coklat'),
        li('Laranja',  'Laranja',  'Oranye',
           ['Vermelho', 'Laranja', 'Amarelo', 'Rosa'],
           ['Merah', 'Oranye', 'Kuning', 'Merah muda']),
      ],
    },
    {
      id: 'pt-food', title: 'lessonFood', subtitle: 'lessonFoodSub',
      exercises: [
        mc('Pão',     'Pão',     'Roti',   ['Pão', 'Leite', 'Carne', 'Queijo']),
        li('Leite',   'Leite',   'Susu',
           ['Água', 'Leite', 'Sumo', 'Café'],
           ['Air', 'Susu', 'Jus', 'Kopi']),
        ta('Fruta',   'Fruta',   'Buah'),
        mcM('Carne',  'Carne',   'Daging',
           ['Peixe', 'Fruta', 'Carne', 'Pão'],
           ['Ikan', 'Buah', 'Daging', 'Roti']),
        sp('Arroz',   'Arroz',   'Nasi'),
        mc('Peixe',   'Peixe',   'Ikan',   ['Peixe', 'Carne', 'Ovo', 'Queijo']),
        ta('Café',    'Café',    'Kopi'),
        li('Água',    'Água',    'Air',
           ['Leite', 'Sumo', 'Café', 'Água'],
           ['Susu', 'Jus', 'Kopi', 'Air']),
      ],
    },
    {
      id: 'pt-family', title: 'lessonFamily', subtitle: 'lessonFamilySub',
      exercises: [
        mc('Pai',     'Pai',     'Ayah',   ['Pai', 'Mãe', 'Irmão', 'Filho']),
        li('Mãe',     'Mãe',     'Ibu',
           ['Pai', 'Mãe', 'Avô', 'Avó'],
           ['Ayah', 'Ibu', 'Kakek', 'Nenek']),
        ta('Irmão',   'Irmão',   'Kakak laki-laki'),
        mcM('Avô',    'Avô',     'Kakek',
           ['Pai', 'Avô', 'Filho', 'Marido'],
           ['Ayah', 'Kakek', 'Anak laki-laki', 'Suami']),
        sp('Avó',     'Avó',     'Nenek'),
        mc('Filho',   'Filho',   'Anak laki-laki', ['Filho', 'Filha', 'Pai', 'Mãe']),
        ta('Família', 'Família', 'Keluarga'),
        li('Marido',  'Marido',  'Suami',
           ['Esposa', 'Marido', 'Irmão', 'Pai'],
           ['Istri', 'Suami', 'Kakak', 'Ayah']),
      ],
    },
    {
      id: 'pt-body', title: 'lessonBody', subtitle: 'lessonBodySub',
      exercises: [
        mc('Cabeça',  'Cabeça',  'Kepala', ['Cabeça', 'Braço', 'Pé', 'Mão']),
        li('Olho',    'Olho',    'Mata',
           ['Nariz', 'Olho', 'Boca', 'Orelha'],
           ['Hidung', 'Mata', 'Mulut', 'Telinga']),
        ta('Nariz',   'Nariz',   'Hidung'),
        mcM('Boca',   'Boca',    'Mulut',
           ['Nariz', 'Boca', 'Olho', 'Orelha'],
           ['Hidung', 'Mulut', 'Mata', 'Telinga']),
        sp('Mão',     'Mão',     'Tangan'),
        mc('Orelha',  'Orelha',  'Telinga', ['Orelha', 'Olho', 'Boca', 'Nariz']),
        ta('Cabelo',  'Cabelo',  'Rambut'),
        li('Coração', 'Coração', 'Jantung',
           ['Pulmão', 'Fígado', 'Coração', 'Estômago'],
           ['Paru-paru', 'Hati', 'Jantung', 'Perut']),
      ],
    },
    {
      id: 'pt-verbs', title: 'lessonVerbs', subtitle: 'lessonVerbsSub',
      exercises: [
        mc('comer',    'comer',    'makan',    ['comer', 'beber', 'brincar', 'trabalhar']),
        ta('beber',    'beber',    'minum'),
        mcM('estudar', 'estudar',  'belajar',
            ['comer', 'beber', 'estudar', 'trabalhar'],
            ['makan', 'minum', 'belajar', 'bekerja']),
        mc('trabalhar','trabalhar','bekerja',  ['trabalhar', 'brincar', 'ler', 'ir']),
        ta('brincar',  'brincar',  'bermain'),
        mc('ler',      'ler',      'membaca',  ['ler', 'escrever', 'comprar', 'comer']),
        ta('escrever', 'escrever', 'menulis'),
        mcM('comprar', 'comprar',  'membeli',
            ['ler', 'escrever', 'comprar', 'vender'],
            ['membaca', 'menulis', 'membeli', 'menjual']),
        mc('ir',       'ir',       'pergi',    ['ir', 'vir', 'morar', 'voltar']),
        ta('morar',    'morar',    'tinggal'),
        ta('vir',      'vir / chegar', 'datang'),
      ],
    },
    {
      id: 'pt-places', title: 'lessonPlaces', subtitle: 'lessonPlacesSub',
      exercises: [
        mc('mercado',     'mercado',    'pasar',   ['mercado', 'escola', 'escritório', 'parque']),
        ta('escola',      'escola',     'sekolah'),
        mcM('escritório', 'escritório', 'kantor',
            ['mercado', 'escola', 'escritório', 'restaurante'],
            ['pasar', 'sekolah', 'kantor', 'restoran']),
        mc('parque',      'parque',     'taman',   ['parque', 'restaurante', 'casa', 'mercado']),
        mc('restaurante', 'restaurante','restoran', ['restaurante', 'mercado', 'teatro', 'biblioteca']),
        ta('casa',        'casa',       'rumah'),
        mcM('hospital',   'hospital',   'rumah sakit',
            ['hospital', 'farmácia', 'aeroporto', 'escola'],
            ['rumah sakit', 'apotek', 'bandara', 'sekolah']),
        mc('farmácia',    'farmácia',   'apotek',  ['farmácia', 'hospital', 'escritório', 'parque']),
        ta('aeroporto',   'aeroporto',  'bandara'),
        mc('biblioteca',  'biblioteca', 'perpustakaan', ['biblioteca', 'teatro', 'restaurante', 'casa']),
        mcM('teatro',     'teatro',     'teater',
            ['teatro', 'biblioteca', 'restaurante', 'parque'],
            ['teater', 'perpustakaan', 'restoran', 'taman']),
        mc('igreja',      'igreja',     'gereja',  ['igreja', 'escola', 'hospital', 'farmácia']),
      ],
    },
    {
      id: 'pt-questions', title: 'lessonQuestions', subtitle: 'lessonQuestionsSub',
      exercises: [
        mc('quem',         'quem',           'siapa',      ['quem', 'o que', 'onde', 'quando']),
        ta('o que',        'o que',          'apa'),
        mcM('quando',      'quando',         'kapan',
            ['quem', 'o que', 'onde', 'quando'],
            ['siapa', 'apa', 'di mana', 'kapan']),
        mc('como',         'como',           'bagaimana',  ['como', 'quanto', 'porquê', 'quem']),
        ta('porquê',      'porquê',        'mengapa'),
        mc('quanto',       'quanto / quantos','berapa',    ['quanto', 'quando', 'onde', 'qual']),
        ta('qual',         'qual',           'yang mana'),
        mc('para onde',    'para onde',      'ke mana',    ['para onde', 'de onde', 'onde', 'quando']),
        ta('de onde',      'de onde',        'dari mana'),
        mc('a que horas',  'a que horas',    'jam berapa', ['a que horas', 'quanto tempo', 'quando', 'como']),
        ta('quanto tempo', 'quanto tempo',   'berapa lama'),
        mc('Onde fica…?',  'Onde fica…?',   'Di mana…?',  ['Onde fica…?', 'Quanto custa?', 'Como se chama?', 'Tudo bem?']),
        li('Tudo bem?',      'Apa kabar?',
           ['Tudo bem?', 'Qual é o seu nome?', 'De onde é?', 'Quanto custa?'],
           ['Apa kabar?', 'Siapa namamu?', 'Dari mana?', 'Berapa harganya?']),
        sp('Quanto custa?','Quanto custa?',  'Berapa harganya?'),
      ],
    },
    {
      id: 'pt-word-matching',
      title: 'lessonWordMatching',
      subtitle: 'lessonWordMatchingSub',
      exercises: [
        tut(
          'Lê as frases. Escolhe do quadro abaixo a única palavra que corresponde a cada frase. Há três palavras a mais.',
          'Baca kalimat-kalimat berikut. Pilih dari kotak di bawah satu kata yang sesuai dengan setiap kalimat. Ada tiga kata yang tidak dipakai.',
          'O que se usa para guardar documentos e papéis importantes.',
          'pasta',
          'pasta',
          'map'
        ),
        wm('O que se usa para proteger da chuva quando está a chover.',
           'guarda-chuva',
           ['chapéu', 'cachecol', 'casaco', 'camisola', 'guarda-chuva', 'mochila', 'meias', 'chinelos'],
           'guarda-chuva', 'payung'),
        wm('O que se calça no verão quando está calor.',
           'chinelos',
           ['chapéu', 'cachecol', 'casaco', 'camisola', 'guarda-chuva', 'mochila', 'meias', 'chinelos'],
           'chinelos', 'sandal'),
        wm('O que se coloca à volta do pescoço para proteger do frio.',
           'cachecol',
           ['chapéu', 'cachecol', 'casaco', 'camisola', 'guarda-chuva', 'mochila', 'meias', 'chinelos'],
           'cachecol', 'syal'),
        wm('O que os alunos usam para transportar os livros da escola.',
           'mochila',
           ['chapéu', 'cachecol', 'casaco', 'camisola', 'guarda-chuva', 'mochila', 'meias', 'chinelos'],
           'mochila', 'ransel'),
        wm('O que se veste por cima de tudo quando está muito frio.',
           'casaco',
           ['chapéu', 'cachecol', 'casaco', 'camisola', 'guarda-chuva', 'mochila', 'meias', 'chinelos'],
           'casaco', 'jaket'),
      ],
    },
    (() => {
      const _t = 'Na segunda semana de setembro, logo após o verão, o meu pai foi ao meu quarto chamar-me para tomar o pequeno-almoço, como faz sempre. – Bom dia, Ana! Levanta-te, o pequeno-almoço está pronto – disse ele. Eu abri os olhos com dificuldade e respondi com pouca energia: – Já vou… O meu pai abriu a janela e, como eu continuava deitada, voltou a chamar-me: – Ana! Não te atrases, tens escola! Depois do meu pai sair do quarto, aconteceu algo estranho: eu, que, até àquele dia, me levantava facilmente quando ouvia os pássaros a cantar, não conseguia tirar as pernas da cama!';
      return {
        id: 'pt-true-false',
        title: 'lessonTrueFalse',
        subtitle: 'lessonTrueFalseSub',
        exercises: [
          tutRead('Lê o texto e responde às questões.', 'Baca teks berikut dan jawab pertanyaan-pertanyaannya.', _t),
          tf('O verão já acabou.',                                   'true',  _t),
          tf('O pai vai sempre chamar a Ana ao seu quarto.',         'true',  _t),
          tf('A Ana nunca se levanta de manhã.',                     'false', _t),
          tf('Neste dia, a Ana conseguiu levantar-se facilmente.',   'false', _t),
          mcI(
            'Escolhe o título mais adequado para o texto.',
            'Pilih judul yang paling tepat untuk teks ini.',
            ['A escola da Ana', 'Uma manhã preguiçosa', 'O verão da Ana'],
            1
          ),
        ],
      };
    })(),
    ],
	'CIPLE': [],
    'DEPLE': [],
    'DIPLE': [],
    'DAPLE': [],
    'DUPLE': [],
  },

  // ── Indonesian ────────────────────────────────────────
  'id-ID': {
    'BIPA 1': [
    {
      id: 'id-greetings', title: 'lessonGreetings',
      subtitle: 'lessonGreetingsSub',
      exercises: [
        mc('Halo',            'Olá',         'Halo',           ['Halo', 'Terima kasih', 'Ya', 'Selamat tinggal']),
        li('Selamat pagi',    'Bom dia',     'Selamat pagi',
           ['Bom dia', 'Boa tarde', 'Boa noite', 'Adeus'],
           ['Selamat pagi', 'Selamat sore', 'Selamat malam', 'Selamat tinggal']),
        ta('Terima kasih',    'Obrigado',    'Terima kasih'),
        sp('Selamat sore',    'Boa tarde',   'Selamat sore'),
        mcM('Selamat tinggal','Adeus',       'Selamat tinggal',
           ['Olá', 'Por favor', 'Adeus', 'Sim'],
           ['Halo', 'Tolong', 'Selamat tinggal', 'Ya']),
        li('Selamat malam',   'Boa noite',   'Selamat malam',
           ['Bom dia', 'Boa tarde', 'Boa noite', 'Adeus'],
           ['Selamat pagi', 'Selamat sore', 'Selamat malam', 'Selamat tinggal']),
        ta('Tolong',          'Por favor',   'Tolong'),
        sp('Permisi',         'Com licença', 'Permisi'),
      ],
    },
    {
      id: 'id-numbers', title: 'lessonNumbers',
      subtitle: 'lessonNumbersSub',
      exercises: [
        mc('Nol',          'Zero',   'Nol',           ['Nol', 'Sebelas', 'Tiga belas', 'Dua puluh']),
        mc('Satu',   'Um',    'Satu',    ['Satu', 'Dua', 'Tiga', 'Empat']),
        li('Dua',    'Dois',  'Dua',
           ['Um', 'Dois', 'Três', 'Quatro'],
           ['Satu', 'Dua', 'Tiga', 'Empat']),
        ta('Tiga',   'Três',  'Tiga'),
        sp('Empat',  'Quatro','Empat'),
        mcM('Lima',  'Cinco', 'Lima',
           ['Três', 'Quatro', 'Cinco', 'Seis'],
           ['Tiga', 'Empat', 'Lima', 'Enam']),
        li('Enam',   'Seis',  'Enam',
           ['Quatro', 'Cinco', 'Seis', 'Sete'],
           ['Empat', 'Lima', 'Enam', 'Tujuh']),
        ta('Tujuh',  'Sete',  'Tujuh'),
        sp('Delapan','Oito',  'Delapan'),
        mc('Sembilan',     'Nove',   'Sembilan',      ['Tujuh', 'Delapan', 'Sembilan', 'Sepuluh']),
        mc('Sepuluh',      'Dez',    'Sepuluh',       ['Delapan', 'Sembilan', 'Sepuluh', 'Sebelas']),
        mc('Sebelas',      'Onze',   'Sebelas',       ['Nol', 'Sebelas', 'Delapan belas', 'Dua puluh']),
        mc('Tiga belas',   'Treze',  'Tiga belas',    ['Sebelas', 'Tiga belas', 'Delapan belas', 'Dua puluh']),
        mc('Delapan belas','Dezoito','Delapan belas', ['Sebelas', 'Tiga belas', 'Delapan belas', 'Dua puluh']),
        mc('Dua puluh',    'Vinte',  'Dua puluh',     ['Nol', 'Tiga belas', 'Delapan belas', 'Dua puluh']),
      ],
    },
    {
      id: 'id-colors', title: 'lessonColors',
      subtitle: 'lessonColorsSub',
      exercises: [
        mc('Merah',   'Vermelho', 'Merah',  ['Merah', 'Biru', 'Hijau', 'Kuning']),
        li('Biru',    'Azul',     'Biru',
           ['Vermelho', 'Azul', 'Verde', 'Amarelo'],
           ['Merah', 'Biru', 'Hijau', 'Kuning']),
        ta('Hijau',   'Verde',    'Hijau'),
        mcM('Kuning', 'Amarelo',  'Kuning',
           ['Vermelho', 'Azul', 'Verde', 'Amarelo'],
           ['Merah', 'Biru', 'Hijau', 'Kuning']),
        sp('Putih',   'Branco',   'Putih'),
        mc('Hitam',   'Preto',    'Hitam',  ['Hitam', 'Putih', 'Coklat', 'Oranye']),
        ta('Coklat',  'Castanho', 'Coklat'),
        li('Oranye',  'Laranja',  'Oranye',
           ['Vermelho', 'Laranja', 'Amarelo', 'Rosa'],
           ['Merah', 'Oranye', 'Kuning', 'Merah muda']),
      ],
    },
    {
      id: 'id-food', title: 'lessonFood',
      subtitle: 'lessonFoodSub',
      exercises: [
        mc('Nasi',  'Arroz',  'Nasi',  ['Nasi', 'Roti', 'Mie', 'Kentang']),
        li('Ayam',  'Frango', 'Ayam',
           ['Peixe', 'Frango', 'Carne', 'Ovo'],
           ['Ikan', 'Ayam', 'Daging', 'Telur']),
        ta('Ikan',  'Peixe',  'Ikan'),
        mcM('Buah', 'Fruta',  'Buah',
           ['Legumes', 'Arroz', 'Fruta', 'Pão'],
           ['Sayur', 'Nasi', 'Buah', 'Roti']),
        sp('Kopi',  'Café',   'Kopi'),
        mc('Air',   'Água',   'Air',   ['Air', 'Susu', 'Jus', 'Kopi']),
        ta('Roti',  'Pão',    'Roti'),
        li('Telur', 'Ovo',    'Telur',
           ['Queijo', 'Ovo', 'Manteiga', 'Leite'],
           ['Keju', 'Telur', 'Mentega', 'Susu']),
      ],
    },
    {
      id: 'id-family', title: 'lessonFamily',
      subtitle: 'lessonFamilySub',
      exercises: [
        mc('Ayah',    'Pai',      'Ayah',   ['Ayah', 'Ibu', 'Kakak', 'Adik']),
        li('Ibu',     'Mãe',      'Ibu',
           ['Pai', 'Mãe', 'Irmão', 'Irmã'],
           ['Ayah', 'Ibu', 'Kakak', 'Adik']),
        ta('Kakak',   'Irmão mais velho', 'Kakak'),
        mcM('Adik',   'Irmão mais novo',  'Adik',
           ['Irmão mais velho', 'Irmão mais novo', 'Pai', 'Filho'],
           ['Kakak', 'Adik', 'Ayah', 'Anak']),
        sp('Kakek',   'Avô',      'Kakek'),
        mc('Nenek',   'Avó',      'Nenek',  ['Nenek', 'Kakek', 'Ibu', 'Adik']),
        ta('Suami',   'Marido',   'Suami'),
        li('Keluarga','Família',  'Keluarga',
           ['Família', 'Amigos', 'Vizinhos', 'Parentes'],
           ['Keluarga', 'Teman', 'Tetangga', 'Saudara']),
      ],
    },
    {
      id: 'id-body', title: 'lessonBody', subtitle: 'lessonBodySub',
      exercises: [
        mc('Kepala',  'Cabeça',  'Kepala',  ['Kepala', 'Tangan', 'Kaki', 'Mata']),
        li('Mata',    'Olho',    'Mata',
           ['Nariz', 'Olho', 'Boca', 'Orelha'],
           ['Hidung', 'Mata', 'Mulut', 'Telinga']),
        ta('Hidung',  'Nariz',   'Hidung'),
        mcM('Mulut',  'Boca',    'Mulut',
           ['Nariz', 'Boca', 'Olho', 'Orelha'],
           ['Hidung', 'Mulut', 'Mata', 'Telinga']),
        sp('Tangan',  'Mão',     'Tangan'),
        mc('Telinga', 'Orelha',  'Telinga', ['Telinga', 'Mata', 'Mulut', 'Hidung']),
        ta('Rambut',  'Cabelo',  'Rambut'),
        li('Jantung', 'Coração', 'Jantung',
           ['Pulmão', 'Fígado', 'Coração', 'Estômago'],
           ['Paru-paru', 'Hati', 'Jantung', 'Perut']),
      ],
    },
    {
      id: 'id-verbs', title: 'lessonVerbs',
      subtitle: 'lessonVerbsSub',
      exercises: [
        mc('makan',   'comer',        'makan',   ['makan', 'minum', 'bermain', 'bekerja']),
        ta('minum',   'beber',        'minum'),
        mcM('belajar','estudar',      'belajar',
            ['comer', 'beber', 'estudar', 'trabalhar'],
            ['makan', 'minum', 'belajar', 'bekerja']),
        mc('bekerja', 'trabalhar',    'bekerja', ['bekerja', 'bermain', 'membaca', 'pergi']),
        ta('bermain', 'brincar',      'bermain'),
        mc('membaca', 'ler',          'membaca', ['membaca', 'menulis', 'membeli', 'makan']),
        ta('menulis', 'escrever',     'menulis'),
        mcM('membeli','comprar',      'membeli',
            ['ler', 'escrever', 'comprar', 'vender'],
            ['membaca', 'menulis', 'membeli', 'menjual']),
        mc('pergi',   'ir',           'pergi',   ['pergi', 'datang', 'tinggal', 'kembali']),
        ta('tinggal', 'morar',        'tinggal'),
        ta('datang',  'vir / chegar', 'datang'),
      ],
    },
    {
      id: 'id-places', title: 'lessonPlaces',
      subtitle: 'lessonPlacesSub',
      exercises: [
        mc('pasar',        'mercado',    'pasar',       ['pasar', 'sekolah', 'kantor', 'taman']),
        ta('sekolah',      'escola',     'sekolah'),
        mcM('kantor',      'escritório', 'kantor',
            ['mercado', 'escola', 'escritório', 'restaurante'],
            ['pasar', 'sekolah', 'kantor', 'restoran']),
        mc('taman',        'parque',     'taman',       ['taman', 'restoran', 'rumah', 'pasar']),
        mc('restoran',     'restaurante','restoran',    ['restoran', 'pasar', 'teater', 'perpustakaan']),
        ta('rumah',        'casa',       'rumah'),
        mcM('rumah sakit', 'hospital',   'rumah sakit',
            ['hospital', 'farmácia', 'aeroporto', 'escola'],
            ['rumah sakit', 'apotek', 'bandara', 'sekolah']),
        mc('apotek',       'farmácia',   'apotek',      ['apotek', 'rumah sakit', 'kantor', 'taman']),
        ta('bandara',      'aeroporto',  'bandara'),
        mc('perpustakaan', 'biblioteca', 'perpustakaan',['perpustakaan', 'teater', 'restoran', 'rumah']),
        mcM('teater',      'teatro',     'teater',
            ['teatro', 'biblioteca', 'restaurante', 'parque'],
            ['teater', 'perpustakaan', 'restoran', 'taman']),
        mc('gereja',       'igreja',     'gereja',      ['gereja', 'sekolah', 'rumah sakit', 'apotek']),
      ],
    },
    {
      id: 'id-questions', title: 'lessonQuestions',
      subtitle: 'lessonQuestionsSub',
      exercises: [
        mc('siapa',       'quem',            'siapa',      ['siapa', 'apa', 'di mana', 'kapan']),
        ta('apa',         'o que',           'apa'),
        mcM('kapan',      'quando',          'kapan',
            ['quem', 'o que', 'onde', 'quando'],
            ['siapa', 'apa', 'di mana', 'kapan']),
        mc('bagaimana',   'como',            'bagaimana',  ['bagaimana', 'berapa', 'mengapa', 'siapa']),
        ta('mengapa',     'porquê',         'mengapa'),
        mc('berapa',      'quanto / quantos','berapa',     ['berapa', 'kapan', 'di mana', 'yang mana']),
        ta('yang mana',   'qual',            'yang mana'),
        mc('ke mana',     'para onde',       'ke mana',    ['ke mana', 'dari mana', 'di mana', 'kapan']),
        ta('dari mana',   'de onde',         'dari mana'),
        mc('jam berapa',  'a que horas',     'jam berapa', ['jam berapa', 'berapa lama', 'kapan', 'bagaimana']),
        ta('berapa lama', 'quanto tempo',    'berapa lama'),
        mc('Di mana…?',   'Onde fica…?',    'Di mana…?',  ['Di mana…?', 'Berapa harganya?', 'Siapa namamu?', 'Apa kabar?']),
        li('Apa kabar?',  'Tudo bem?',       'Apa kabar?',
           ['Tudo bem?', 'Qual é o seu nome?', 'De onde é?', 'Quanto custa?'],
           ['Apa kabar?', 'Siapa namamu?', 'Dari mana?', 'Berapa harganya?']),
        sp('Berapa harganya?','Quanto custa?','Berapa harganya?'),
      ],
    },
    ],
    'BIPA 2': [
    {
      id: 'id-daily-life', title: 'Kehidupan Sehari-hari',
      subtitle: 'Waktu, Tempat & Kata Hubung…',
      exercises: [
        mc('sering',     'frequentemente',   'sering',     ['sering', 'selalu', 'jarang', 'kadang']),
        ta('selalu',     'sempre',           'selalu'),
        mcM('jarang',    'raramente',        'jarang',
            ['sempre', 'frequentemente', 'raramente', 'às vezes'],
            ['selalu', 'sering', 'jarang', 'kadang-kadang']),
        mc('kemarin',    'ontem',            'kemarin',    ['kemarin', 'hari ini', 'besok', 'tadi']),
        ta('hari ini',   'hoje',             'hari ini'),
        mc('besok',      'amanhã',           'besok',      ['besok', 'kemarin', 'nanti', 'lusa']),
        ta('pagi',       'manhã',            'pagi'),
        mcM('malam',     'noite',            'malam',
            ['manhã', 'tarde', 'noite', 'madrugada'],
            ['pagi', 'siang', 'malam', 'dini hari']),
        mc('untuk',      'para',             'untuk',      ['untuk', 'karena', 'tetapi', 'jika']),
        ta('karena',     'porque',           'karena'),
        mc('tetapi',     'mas / porém',      'tetapi',     ['tetapi', 'untuk', 'karena', 'jika']),
        ta('tidak',      'não',              'tidak'),
        mcM('bukan',     'não é (subst.)',   'bukan',
            ['não', 'não é (subst.)', 'talvez', 'sim'],
            ['tidak', 'bukan', 'mungkin', 'ya']),
        mc('dari',       'de (origem)',      'dari',       ['dari', 'ke', 'di', 'pada']),
        ta('ke',         'para (direção)',   'ke'),
        mc('di',         'em / no / na',     'di',         ['di', 'ke', 'dari', 'oleh']),
        ta('restoran',   'restaurante',      'restoran'),
        mcM('toko',      'loja',             'toko',
            ['restaurante', 'loja', 'mercado', 'hotel'],
            ['restoran', 'toko', 'pasar', 'hotel']),
        mc('hotel',      'hotel',            'hotel',      ['hotel', 'toko', 'rumah', 'restoran']),
        ta('jalan',      'rua / caminho',    'jalan'),
      ],
    },
    ],
    'BIPA 3': [
    {
      id: 'id-weather-nature', title: 'Cuaca & Alam',
      subtitle: 'Waktu, Cuaca, Alam & Hubungan…',
      exercises: [
        mc('panas',      'quente',           'panas',      ['panas', 'dingin', 'hangat', 'sejuk']),
        ta('dingin',     'frio',             'dingin'),
        mcM('hujan',     'chuva',            'hujan',
            ['sol', 'chuva', 'vento', 'nuvem'],
            ['matahari', 'hujan', 'angin', 'awan']),
        mc('angin',      'vento',            'angin',      ['angin', 'hujan', 'matahari', 'awan']),
        ta('matahari',   'sol',              'matahari'),
        mc('langit',     'céu',              'langit',     ['langit', 'awan', 'bintang', 'bulan']),
        ta('laut',       'mar',              'laut'),
        mcM('gunung',    'montanha',         'gunung',
            ['mar', 'montanha', 'floresta', 'rio'],
            ['laut', 'gunung', 'hutan', 'sungai']),
        mc('sudah',      'já (passado)',      'sudah',      ['sudah', 'sedang', 'akan', 'belum']),
        ta('sedang',     'estar + -ndo',     'sedang'),
        mcM('akan',      'vai / irá (futuro)', 'akan',
            ['já (passado)', 'estar + -ndo', 'vai / irá (futuro)', 'ainda não'],
            ['sudah', 'sedang', 'akan', 'belum']),
        mc('cuaca',      'tempo / clima',    'cuaca',      ['cuaca', 'musim', 'iklim', 'suhu']),
        ta('musim',      'estação do ano',   'musim'),
        mcM('kota',      'cidade',           'kota',
            ['cidade', 'aldeia', 'país', 'ilha'],
            ['kota', 'desa', 'negara', 'pulau']),
        mc('desa',       'aldeia / vila',    'desa',       ['desa', 'kota', 'kampung', 'negara']),
        ta('perjalanan', 'viagem',           'perjalanan'),
        mc('walaupun',   'embora / apesar de', 'walaupun', ['walaupun', 'karena', 'tetapi', 'jika']),
        ta('sungai',     'rio',              'sungai'),
        mc('hutan',      'floresta',         'hutan',      ['hutan', 'gunung', 'laut', 'sungai']),
        ta('awan',       'nuvem',            'awan'),
      ],
    },
    ],
    'BIPA 4': [
    {
      id: 'id-society-opinion', title: 'Masyarakat & Opini',
      subtitle: 'Modal, Opini, Masyarakat & Lingkungan…',
      exercises: [
        mc('harus',      'deve / tem de',    'harus',      ['harus', 'perlu', 'boleh', 'ingin']),
        ta('perlu',      'precisar / necessário', 'perlu'),
        mcM('boleh',     'pode / é permitido', 'boleh',
            ['tem de', 'precisar', 'pode / é permitido', 'quer'],
            ['harus', 'perlu', 'boleh', 'mau']),
        mc('dilarang',   'proibido',         'dilarang',   ['dilarang', 'diwajibkan', 'diizinkan', 'disarankan']),
        ta('pendapat',   'opinião',          'pendapat'),
        mcM('setuju',    'concordar / de acordo', 'setuju',
            ['discordar', 'concordar / de acordo', 'duvidar', 'ignorar'],
            ['menolak', 'setuju', 'meragukan', 'mengabaikan']),
        mc('menolak',    'recusar / discordar', 'menolak',  ['menolak', 'setuju', 'menerima', 'mendukung']),
        ta('masyarakat', 'sociedade',        'masyarakat'),
        mc('pemerintah', 'governo',          'pemerintah', ['pemerintah', 'masyarakat', 'negara', 'parlemen']),
        ta('kebijakan',  'política / medida','kebijakan'),
        mcM('dampak',    'impacto',          'dampak',
            ['benefício', 'impacto', 'solução', 'problema'],
            ['manfaat', 'dampak', 'solusi', 'masalah']),
        mc('manfaat',    'benefício',        'manfaat',    ['manfaat', 'kerugian', 'dampak', 'solusi']),
        ta('kerugian',   'prejuízo / desvantagem', 'kerugian'),
        mc('lingkungan', 'ambiente',         'lingkungan', ['lingkungan', 'alam', 'ekosistem', 'iklim']),
        ta('teknologi',  'tecnologia',       'teknologi'),
        mcM('masalah',   'problema',         'masalah',
            ['solução', 'problema', 'causa', 'efeito'],
            ['solusi', 'masalah', 'sebab', 'akibat']),
        mc('solusi',     'solução',          'solusi',     ['solusi', 'masalah', 'pendapat', 'kebijakan']),
        ta('budaya',     'cultura',          'budaya'),
        mc('sejarah',    'história',         'sejarah',    ['sejarah', 'budaya', 'tradisi', 'seni']),
        ta('ekonomi',    'economia',         'ekonomi'),
      ],
    },
    ],
    'BIPA 5': [
    {
      id: 'id-academic', title: 'Akademik & Profesional',
      subtitle: 'Penelitian, Analisis & Profesi…',
      exercises: [
        mc('penelitian', 'pesquisa',         'penelitian', ['penelitian', 'studi', 'kajian', 'survei']),
        ta('kesimpulan', 'conclusão',        'kesimpulan'),
        mcM('argumen',   'argumento',        'argumen',
            ['pesquisa', 'argumento', 'hipótese', 'análise'],
            ['penelitian', 'argumen', 'hipotesis', 'analisis']),
        mc('analisis',   'análise',          'analisis',   ['analisis', 'sintesis', 'evaluasi', 'deskripsi']),
        ta('hipotesis',  'hipótese',         'hipotesis'),
        mcM('teori',     'teoria',           'teori',
            ['teoria', 'fato', 'dado', 'evidência'],
            ['teori', 'fakta', 'data', 'bukti']),
        mc('bukti',      'evidência / prova','bukti',      ['bukti', 'data', 'fakta', 'teori']),
        ta('laporan',    'relatório',        'laporan'),
        mc('inovasi',    'inovação',         'inovasi',    ['inovasi', 'kreasi', 'solusi', 'strategi']),
        ta('strategi',   'estratégia',       'strategi'),
        mcM('kolaborasi','colaboração',      'kolaborasi',
            ['colaboração', 'competição', 'cooperação', 'integração'],
            ['kolaborasi', 'kompetisi', 'kerja sama', 'integrasi']),
        mc('evaluasi',   'avaliação',        'evaluasi',   ['evaluasi', 'analisis', 'penilaian', 'review']),
        ta('efisien',    'eficiente',        'efisien'),
        mc('relevan',    'relevante',        'relevan',    ['relevan', 'akurat', 'valid', 'objektif']),
        ta('akurat',     'preciso / exato',  'akurat'),
        mcM('kompeten',  'competente',       'kompeten',
            ['competente', 'profissional', 'experiente', 'habilidoso'],
            ['kompeten', 'profesional', 'berpengalaman', 'terampil']),
        mc('metodologi', 'metodologia',      'metodologi', ['metodologi', 'metode', 'prosedur', 'teknik']),
        ta('kriteria',   'critério',         'kriteria'),
        mc('presentasi', 'apresentação',     'presentasi', ['presentasi', 'laporan', 'debat', 'seminar']),
        ta('negosiasi',  'negociação',       'negosiasi'),
      ],
    },
    ],
    'BIPA 6': [
    {
      id: 'id-formal-critical', title: 'Bahasa Formal & Kritis',
      subtitle: 'Wacana, Retorika & Analisis…',
      exercises: [
        mc('globalisasi','globalização',     'globalisasi', ['globalisasi', 'modernisasi', 'urbanisasi', 'internasionalisasi']),
        ta('keberlanjutan','sustentabilidade','keberlanjutan'),
        mcM('koherensi', 'coerência',        'koherensi',
            ['coerência', 'coesão', 'fluência', 'clareza'],
            ['koherensi', 'kohesi', 'kelancaran', 'kejelasan']),
        mc('fenomena',   'fenômeno',         'fenomena',   ['fenomena', 'gejala', 'peristiwa', 'kejadian']),
        ta('sintesis',   'síntese',          'sintesis'),
        mcM('retorika',  'retórica',         'retorika',
            ['retórica', 'dialética', 'lógica', 'argumentação'],
            ['retorika', 'dialektika', 'logika', 'argumentasi']),
        mc('paradigma',  'paradigma',        'paradigma',  ['paradigma', 'kerangka', 'model', 'teori']),
        ta('hegemoni',   'hegemonia',        'hegemoni'),
        mc('empiris',    'empírico',         'empiris',    ['empiris', 'teoritis', 'deduktif', 'induktif']),
        ta('interpretasi','interpretação',   'interpretasi'),
        mcM('deduktif',  'dedutivo',         'deduktif',
            ['indutivo', 'dedutivo', 'analítico', 'sintético'],
            ['induktif', 'deduktif', 'analitik', 'sintetik']),
        mc('induktif',   'indutivo',         'induktif',   ['induktif', 'deduktif', 'empiris', 'abduktif']),
        ta('konsensus',  'consenso',         'konsensus'),
        mc('legitimasi', 'legitimidade',     'legitimasi', ['legitimasi', 'otoritas', 'kekuasaan', 'kedaulatan']),
        ta('diskursus',  'discurso',         'diskursus'),
        mcM('epistemologi','epistemologia',  'epistemologi',
            ['epistemologia', 'ontologia', 'metodologia', 'axiologia'],
            ['epistemologi', 'ontologi', 'metodologi', 'aksiologi']),
        mc('dialektika', 'dialética',        'dialektika', ['dialektika', 'logika', 'retorika', 'epistemologi']),
        ta('ontologi',   'ontologia',        'ontologi'),
        mc('abstrak',    'abstrato / resumo','abstrak',    ['abstrak', 'konkret', 'teoritis', 'empiris']),
        ta('metodologi', 'metodologia',      'metodologi'),
      ],
    },
    ],
  },

  // ── French (now unlocked) ─────────────────────────────
  'fr-FR': {
    'DELF A1': [
    {
      id: 'fr-greetings', title: 'lessonGreetings', subtitle: 'lessonGreetingsSub',
      exercises: [
        mc('Bonjour',         'Olá',         'Halo',           ['Bonjour', 'Merci', 'Oui', 'Au revoir']),
        li('Au revoir',       'Adeus',       'Selamat tinggal',
           ['Olá', 'Adeus', 'Obrigado', 'Bom dia'],
           ['Halo', 'Selamat tinggal', 'Terima kasih', 'Selamat pagi']),
        ta('Merci',           'Obrigado',    'Terima kasih'),
        sp('Bonjour',         'Olá',         'Halo'),
        mcM('Bonne nuit',        'Boa noite',   'Selamat malam',
           ['Bom dia', 'Boa tarde', 'Boa noite', 'Adeus'],
           ['Selamat pagi', 'Selamat sore', 'Selamat malam', 'Selamat tinggal']),
        li("S'il vous plaît", 'Por favor',   'Tolong',
           ['Obrigado', 'Por favor', 'Com licença', 'Adeus'],
           ['Terima kasih', 'Tolong', 'Permisi', 'Selamat tinggal']),
        ta('Excusez-moi',     'Com licença', 'Permisi'),
        sp('Merci',           'Obrigado',    'Terima kasih'),
      ],
    },
    {
      id: 'fr-numbers', title: 'lessonNumbers', subtitle: 'lessonNumbersSub',
      exercises: [
        mc('Un',     'Um',    'Satu',    ['Un', 'Deux', 'Trois', 'Quatre']),
        li('Deux',   'Dois',  'Dua',
           ['Um', 'Dois', 'Três', 'Quatro'],
           ['Satu', 'Dua', 'Tiga', 'Empat']),
        ta('Trois',  'Três',  'Tiga'),
        sp('Quatre', 'Quatro','Empat'),
        mcM('Cinq',  'Cinco', 'Lima',
           ['Três', 'Quatro', 'Cinco', 'Seis'],
           ['Tiga', 'Empat', 'Lima', 'Enam']),
        li('Six',    'Seis',  'Enam',
           ['Quatro', 'Cinco', 'Seis', 'Sete'],
           ['Empat', 'Lima', 'Enam', 'Tujuh']),
        ta('Sept',   'Sete',  'Tujuh'),
        sp('Huit',   'Oito',  'Delapan'),
      ],
    },
    {
      id: 'fr-colors', title: 'lessonColors', subtitle: 'lessonColorsSub',
      exercises: [
        mc('Rouge',   'Vermelho', 'Merah',   ['Rouge', 'Bleu', 'Vert', 'Jaune']),
        li('Bleu',    'Azul',     'Biru',
           ['Vermelho', 'Azul', 'Verde', 'Amarelo'],
           ['Merah', 'Biru', 'Hijau', 'Kuning']),
        ta('Vert',    'Verde',    'Hijau'),
        mcM('Jaune',  'Amarelo',  'Kuning',
           ['Vermelho', 'Azul', 'Verde', 'Amarelo'],
           ['Merah', 'Biru', 'Hijau', 'Kuning']),
        sp('Blanc',   'Branco',   'Putih'),
        mc('Noir',    'Preto',    'Hitam',   ['Noir', 'Blanc', 'Marron', 'Orange']),
        ta('Marron',  'Castanho', 'Coklat'),
        li('Orange',  'Laranja',  'Oranye',
           ['Vermelho', 'Laranja', 'Amarelo', 'Rosa'],
           ['Merah', 'Oranye', 'Kuning', 'Merah muda']),
      ],
    },
    {
      id: 'fr-food', title: 'lessonFood', subtitle: 'lessonFoodSub',
      exercises: [
        mc('Pain',     'Pão',     'Roti',   ['Pain', 'Lait', 'Viande', 'Fromage']),
        li('Lait',     'Leite',   'Susu',
           ['Água', 'Leite', 'Sumo', 'Café'],
           ['Air', 'Susu', 'Jus', 'Kopi']),
        ta('Fruit',    'Fruta',   'Buah'),
        mcM('Viande',  'Carne',   'Daging',
           ['Peixe', 'Fruta', 'Carne', 'Pão'],
           ['Ikan', 'Buah', 'Daging', 'Roti']),
        sp('Riz',      'Arroz',   'Nasi'),
        mc('Poisson',  'Peixe',   'Ikan',   ['Poisson', 'Viande', 'Œuf', 'Fromage']),
        ta('Café',     'Café',    'Kopi'),
        li('Eau',      'Água',    'Air',
           ['Leite', 'Sumo', 'Café', 'Água'],
           ['Susu', 'Jus', 'Kopi', 'Air']),
      ],
    },
    {
      id: 'fr-family', title: 'lessonFamily', subtitle: 'lessonFamilySub',
      exercises: [
        mc('Père',        'Pai',     'Ayah',   ['Père', 'Mère', 'Frère', 'Fils']),
        li('Mère',        'Mãe',     'Ibu',
           ['Pai', 'Mãe', 'Avô', 'Avó'],
           ['Ayah', 'Ibu', 'Kakek', 'Nenek']),
        ta('Frère',       'Irmão',   'Kakak laki-laki'),
        mcM('Grand-père', 'Avô',     'Kakek',
           ['Pai', 'Avô', 'Filho', 'Marido'],
           ['Ayah', 'Kakek', 'Anak laki-laki', 'Suami']),
        sp('Grand-mère',  'Avó',     'Nenek'),
        mc('Fils',        'Filho',   'Anak laki-laki', ['Fils', 'Fille', 'Père', 'Mère']),
        ta('Mari',        'Marido',  'Suami'),
        li('Famille',     'Família', 'Keluarga',
           ['Família', 'Amigos', 'Vizinhos', 'Casa'],
           ['Keluarga', 'Teman', 'Tetangga', 'Rumah']),
      ],
    },
    {
      id: 'fr-body', title: 'lessonBody', subtitle: 'lessonBodySub',
      exercises: [
        mc('Tête',     'Cabeça',  'Kepala', ['Tête', 'Bras', 'Pied', 'Main']),
        li('Œil',      'Olho',    'Mata',
           ['Nariz', 'Olho', 'Boca', 'Orelha'],
           ['Hidung', 'Mata', 'Mulut', 'Telinga']),
        ta('Nez',      'Nariz',   'Hidung'),
        mcM('Bouche',  'Boca',    'Mulut',
           ['Nariz', 'Boca', 'Olho', 'Orelha'],
           ['Hidung', 'Mulut', 'Mata', 'Telinga']),
        sp('Main',     'Mão',     'Tangan'),
        mc('Oreille',  'Orelha',  'Telinga', ['Oreille', 'Œil', 'Bouche', 'Nez']),
        ta('Cheveux',  'Cabelo',  'Rambut'),
        li('Cœur',     'Coração', 'Jantung',
           ['Pulmão', 'Fígado', 'Coração', 'Estômago'],
           ['Paru-paru', 'Hati', 'Jantung', 'Perut']),
      ],
    },
    {
      id: 'fr-verbs', title: 'lessonVerbs', subtitle: 'lessonVerbsSub',
      exercises: [
        mc('manger',    'comer',         'makan',    ['manger', 'boire', 'jouer', 'travailler']),
        ta('boire',     'beber',         'minum'),
        mcM('étudier',  'estudar',       'belajar',
            ['comer', 'beber', 'estudar', 'trabalhar'],
            ['makan', 'minum', 'belajar', 'bekerja']),
        mc('travailler','trabalhar',     'bekerja',  ['travailler', 'jouer', 'lire', 'aller']),
        ta('jouer',     'brincar',       'bermain'),
        mc('lire',      'ler',           'membaca',  ['lire', 'écrire', 'acheter', 'manger']),
        ta('écrire',    'escrever',      'menulis'),
        mcM('acheter',  'comprar',       'membeli',
            ['lire', 'écrire', 'acheter', 'vendre'],
            ['membaca', 'menulis', 'membeli', 'menjual']),
        mc('aller',     'ir',            'pergi',    ['aller', 'venir', 'habiter', 'revenir']),
        ta('habiter',   'morar',         'tinggal'),
        ta('venir',     'vir / chegar',  'datang'),
      ],
    },
    {
      id: 'fr-places', title: 'lessonPlaces', subtitle: 'lessonPlacesSub',
      exercises: [
        mc('marché',       'mercado',    'pasar',       ['marché', 'école', 'bureau', 'parc']),
        ta('école',        'escola',     'sekolah'),
        mcM('bureau',      'escritório', 'kantor',
            ['mercado', 'escola', 'escritório', 'restaurante'],
            ['pasar', 'sekolah', 'kantor', 'restoran']),
        mc('parc',         'parque',     'taman',       ['parc', 'restaurant', 'maison', 'marché']),
        mc('restaurant',   'restaurante','restoran',    ['restaurant', 'marché', 'théâtre', 'bibliothèque']),
        ta('maison',       'casa',       'rumah'),
        mcM('hôpital',     'hospital',   'rumah sakit',
            ['hôpital', 'pharmacie', 'aéroport', 'école'],
            ['rumah sakit', 'apotek', 'bandara', 'sekolah']),
        mc('pharmacie',    'farmácia',   'apotek',      ['pharmacie', 'hôpital', 'bureau', 'parc']),
        ta('aéroport',     'aeroporto',  'bandara'),
        mc('bibliothèque', 'biblioteca', 'perpustakaan',['bibliothèque', 'théâtre', 'restaurant', 'maison']),
        mcM('théâtre',     'teatro',     'teater',
            ['théâtre', 'bibliothèque', 'restaurant', 'parc'],
            ['teater', 'perpustakaan', 'restoran', 'taman']),
        mc('église',       'igreja',     'gereja',      ['église', 'école', 'hôpital', 'pharmacie']),
      ],
    },
    {
      id: 'fr-questions', title: 'lessonQuestions', subtitle: 'lessonQuestionsSub',
      exercises: [
        mc('qui',              'quem',           'siapa',      ['qui', 'quoi', 'où', 'quand']),
        ta('quoi',             'o que',          'apa'),
        mcM('quand',           'quando',         'kapan',
            ['quem', 'o que', 'onde', 'quando'],
            ['siapa', 'apa', 'di mana', 'kapan']),
        mc('comment',          'como',           'bagaimana',  ['comment', 'combien', 'pourquoi', 'qui']),
        ta('pourquoi',         'porquê',        'mengapa'),
        mc('combien',          'quanto / quantos','berapa',    ['combien', 'quand', 'où', 'lequel']),
        ta('lequel',           'qual',           'yang mana'),
        mc('vers où',          'para onde',      'ke mana',    ['vers où', "d'où", 'où', 'quand']),
        ta("d'où",             'de onde',        'dari mana'),
        mc('à quelle heure',   'a que horas',    'jam berapa', ['à quelle heure', 'combien de temps', 'quand', 'comment']),
        ta('combien de temps', 'quanto tempo',   'berapa lama'),
        mc('Où est…?',         'Onde fica…?',   'Di mana…?',  ['Où est…?', 'Combien ça coûte?', 'Comment vous appelez-vous?', 'Comment allez-vous?']),
        li('Comment allez-vous?','Tudo bem?',    'Apa kabar?',
           ['Tudo bem?', 'Qual é o seu nome?', 'De onde é?', 'Quanto custa?'],
           ['Apa kabar?', 'Siapa namamu?', 'Dari mana?', 'Berapa harganya?']),
        sp('Combien ça coûte?','Quanto custa?',  'Berapa harganya?'),
      ],
    },
    ],
    'DELF A2': [],
    'DELF B1': [],
    'DELF B2': [],
    'DALF C1': [],
    'DALF C2': [],
  },
};

// ── Image map ─────────────────────────────────────────────
// Maps ex.target → image path shown in mc / ta exercises.
const IMAGE_MAP = {
  // Greetings
  'Halo':                 'images/hello.png',
  'Olá':                  'images/hello.png',
  'Bonjour':              'images/hello.png',
  'Selamat pagi':         'images/Good Morning.png',
  'Bom dia':              'images/Good Morning.png',
  'Selamat sore':         'images/Good Afternoon.png',
  'Boa tarde':            'images/Good Afternoon.png',
  'Selamat malam':        'images/Good Night.png',
  'Boa noite':            'images/Good Night.png',
  'Bonne nuit':           'images/Good Night.png',
  'Selamat tinggal':      'images/goodbye.png',
  'Adeus':                'images/goodbye.png',
  'Au revoir':            'images/goodbye.png',
  'Terima kasih':         'images/Thank You.png',
  'Obrigado':             'images/Thank You.png',
  'Merci':                'images/Thank You.png',
  'Maaf':                 'images/sorry.png',
  'Desculpe':             'images/sorry.png',
  'Désolé':               'images/sorry.png',
  'Saya tidak mengerti':  "images/I don't understand.png",
  'Não percebo':          "images/I don't understand.png",
  'Je ne comprends pas':  "images/I don't understand.png",
  'Por favor':            'images/please.png',
  'Tolong':               'images/please.png',
  "S'il vous plaît":      'images/please.png',
  'Onde fica…?':          'images/where.png',
  'Di mana…?':            'images/where.png',
  'Où est…?':             'images/where.png',
  // Question words
  'quem':              'images/Who.png',           'siapa':       'images/Who.png',           'qui':               'images/Who.png',
  'o que':             'images/What.png',          'apa':         'images/What.png',          'quoi':              'images/What.png',
  'quando':            'images/When.png',          'kapan':       'images/When.png',          'quand':             'images/When.png',
  'como':              'images/How.png',           'bagaimana':   'images/How.png',           'comment':           'images/How.png',
  'porquê':            'images/Why.png',           'mengapa':     'images/Why.png',           'pourquoi':          'images/Why.png',
  'quanto':            'images/How much.png',      'berapa':      'images/How much.png',      'combien':           'images/How much.png',
  'qual':              'images/Which one.png',     'yang mana':   'images/Which one.png',     'lequel':            'images/Which one.png',
  'para onde':         'images/Where to.png',      'ke mana':     'images/Where to.png',      'vers où':           'images/Where to.png',
  'de onde':           'images/Where from.png',    'dari mana':   'images/Where from.png',    "d'où":              'images/Where from.png',
  'a que horas':       'images/What time.png',     'jam berapa':  'images/What time.png',     'à quelle heure':    'images/What time.png',
  'quanto tempo':      'images/How long.png',      'berapa lama': 'images/How long.png',      'combien de temps':  'images/How long.png',
  'Não entendo':       "images/I don't understand.png", 'Tidak mengerti': "images/I don't understand.png", 'Je ne comprends pas': "images/I don't understand.png",
  // Lesson titles / reading
  'Uma manhã preguiçosa': 'images/Wake up.png',
  // Numbers
  'Satu':    'images/1.png',  'Um':     'images/1.png',  'Un':    'images/1.png',
  'Dua':     'images/2.png',  'Dois':   'images/2.png',  'Deux':  'images/2.png',
  'Tiga':    'images/3.png',  'Três':   'images/3.png',  'Trois': 'images/3.png',
  'Empat':   'images/4.png',  'Quatro': 'images/4.png',  'Quatre':'images/4.png',
  'Lima':    'images/5.png',  'Cinco':  'images/5.png',  'Cinq':  'images/5.png',
  'Enam':    'images/6.png',  'Seis':   'images/6.png',  'Six':   'images/6.png',
  'Tujuh':   'images/7.png',  'Sete':   'images/7.png',  'Sept':  'images/7.png',
  'Delapan': 'images/8.png',  'Oito':   'images/8.png',  'Huit':  'images/8.png',
  'Sembilan':'images/9.png',  'Nove':   'images/9.png',  'Neuf':  'images/9.png',
  'Sepuluh': 'images/10.png', 'Dez':    'images/10.png', 'Dix':   'images/10.png',
  'Nol':           'images/0.png',  'Zero':         'images/0.png',
  'Sebelas':       'images/11.png', 'Onze':         'images/11.png',
  'Tiga belas':    'images/13.png', 'Treze':        'images/13.png',
  'Delapan belas': 'images/18.png', 'Dezoito':      'images/18.png',
  'Dua puluh':     'images/20.png', 'Vinte':        'images/20.png',
  // Clothing
  'chinelos':    'images/Sandals.png',
  'cachecol':    'images/Scarf.png',
  'guarda-chuva':'images/Umbrella.png',
  'mochila':     'images/backpack.png',
  'pasta':       'images/briefcase.png',
  'casaco':      'images/jacket.png',
  // Family
  'Ayah':      'images/father.png',  'Pai':     'images/father.png',  'Père':      'images/father.png',
  'Ibu':       'images/mother.png',  'Mãe':     'images/mother.png',  'Mère':      'images/mother.png',
  'Kakak':     'images/Older brother_sister (kakak).png', 'Irmão': 'images/Older brother_sister (kakak).png', 'Frère': 'images/Older brother_sister (kakak).png',
  'Adik':      'images/adik.png',
  'Kakek':     'images/grandpa.png', 'Avô':     'images/grandpa.png', 'Grand-père':'images/grandpa.png',
  'Nenek':     'images/Granma.png',  'Avó':     'images/Granma.png',  'Grand-mère':'images/Granma.png',
  'Suami':     'images/husband.png', 'Marido':  'images/husband.png', 'Mari':      'images/husband.png',
  'Istri':     'images/wife.png',    'Esposa':  'images/wife.png',    'Femme':     'images/wife.png',
  'Keluarga':  'images/family.png',  'Família': 'images/family.png',  'Famille':   'images/family.png',
  'Anak laki-laki': 'images/son.png', 'Filho': 'images/son.png',    'Fils':      'images/son.png',
  // Colors
  'Merah':   'images/red.png',     'Vermelho': 'images/red.png',     'Rouge':  'images/red.png',
  'Biru':    'images/blue.png',    'Azul':     'images/blue.png',    'Bleu':   'images/blue.png',
  'Hijau':   'images/green.png',   'Verde':    'images/green.png',   'Vert':   'images/green.png',
  'Kuning':  'images/yellow.png',  'Amarelo':  'images/yellow.png',  'Jaune':  'images/yellow.png',
  'Oranye':  'images/orange.png',  'Laranja':  'images/orange.png',  'Orange': 'images/orange.png',
  'Putih':   'images/white.png',   'Branco':   'images/white.png',   'Blanc':  'images/white.png',
  'Hitam':   'images/black.png',   'Preto':    'images/black.png',   'Noir':   'images/black.png',
  'Coklat':  'images/Brown.png',   'Castanho': 'images/Brown.png',   'Marron': 'images/Brown.png',
  // Body
  'Kepala':  'images/Head.png',    'Cabeça':   'images/Head.png',    'Tête':    'images/Head.png',
  'Hidung':  'images/Nose.png',    'Nariz':    'images/Nose.png',    'Nez':     'images/Nose.png',
  'Mulut':   'images/Mouth.png',   'Boca':     'images/Mouth.png',   'Bouche':  'images/Mouth.png',
  'Rambut':  'images/Hair.png',    'Cabelo':   'images/Hair.png',    'Cheveux': 'images/Hair.png',
  'Telinga': 'images/ear.png',     'Orelha':   'images/ear.png',     'Oreille': 'images/ear.png',
  'Tangan':  'images/please.png',  'Mão':      'images/please.png',  'Main':    'images/please.png',
  // Food & drink
  'Nasi':    'images/rice.png',    'Arroz':    'images/rice.png',    'Riz':     'images/rice.png',
  'Ayam':    'images/chicken.png', 'Frango':   'images/chicken.png', 'Poulet':  'images/chicken.png',
  'Ikan':    'images/fish.png',    'Peixe':    'images/fish.png',    'Poisson': 'images/fish.png',
  'Buah':    'images/fruits.png',  'Fruta':    'images/fruits.png',  'Fruit':   'images/fruits.png',
  'Kopi':    'images/coffee.png',  'Café':     'images/coffee.png',
  'Air':     'images/water.png',   'Água':     'images/water.png',   'Eau':     'images/water.png',
  'Roti':    'images/bread.png',   'Pão':      'images/bread.png',   'Pain':    'images/bread.png',
  'Telur':   'images/eggs.png',    'Ovo':      'images/eggs.png',
  'Daging':  'images/meat.png',   'Carne':    'images/meat.png',   'Viande': 'images/meat.png',
  // Verbs
  'makan':   'images/Eat.png',     'comer':    'images/Eat.png',     'manger':    'images/Eat.png',
  'minum':   'images/Drink.png',   'beber':    'images/Drink.png',   'boire':     'images/Drink.png',
  'bekerja': 'images/Work.png',    'trabalhar':'images/Work.png',    'travailler':'images/Work.png',
  'belajar': 'images/Study.png',   'estudar':  'images/Study.png',   'étudier':   'images/Study.png',
  'membaca': 'images/Read.png',    'ler':      'images/Read.png',    'lire':      'images/Read.png',
  'menulis': 'images/Write.png',   'escrever': 'images/Write.png',   'écrire':    'images/Write.png',
  'bermain': 'images/Play.png',    'brincar':  'images/Play.png',    'jouer':     'images/Play.png',
  'membeli': 'images/Buy.png',     'comprar':  'images/Buy.png',     'acheter':   'images/Buy.png',
  'pergi':   'images/Go.png',      'ir':       'images/Go.png',      'aller':     'images/Go.png',
  'datang':  'images/Come.png',    'venir':    'images/Come.png',
  'tinggal': 'images/Live.png',    'morar':    'images/Live.png',    'habiter':   'images/Live.png',
  // Places
  'sekolah':     'images/school.png',    'escola':     'images/school.png',    'école':     'images/school.png',
  'pasar':       'images/Market.png',    'mercado':    'images/Market.png',    'marché':    'images/Market.png',
  'kantor':      'images/Office.png',    'escritório': 'images/Office.png',    'bureau':    'images/Office.png',
  'taman':       'images/Park.png',      'parque':     'images/Park.png',      'parc':      'images/Park.png',
  'restoran':    'images/Restaurant.png','restaurante':'images/Restaurant.png','restaurant':'images/Restaurant.png',
  'rumah sakit': 'images/Hospital.png',  'hospital':   'images/Hospital.png',  'hôpital':   'images/Hospital.png',
  'gereja':      'images/Church.png',    'igreja':     'images/Church.png',    'église':    'images/Church.png',
  'bioskop':     'images/theater.png',   'cinema':     'images/theater.png',   'cinéma':    'images/theater.png',
  'perpustakaan':'images/Library.png',   'biblioteca': 'images/Library.png',   'bibliothèque':'images/Library.png',
  'apotek':      'images/Pharmacy.png',  'farmácia':   'images/Pharmacy.png',  'pharmacie': 'images/Pharmacy.png',
  'bandara':     'images/airport.png',   'aeroporto':  'images/airport.png',   'aéroport':    'images/airport.png',
  'teater':      'images/theater.png',   'teatro':     'images/theater.png',   'théâtre':     'images/theater.png',
  'rumah':       'images/House.png',     'casa':       'images/House.png',     'maison':      'images/House.png',
};

// ── Example sentences ─────────────────────────────────────
// Maps ex.target → example sentence in the target language.
// Use a plain string when one sentence fits all languages;
// use { 'pt-PT': '…', 'fr-FR': '…' } when the same spelling
// appears in multiple languages (e.g. "Café").
const EXAMPLE_MAP = {
  // Greetings
  'Halo':                'Halo, apa kabar?',
  'Olá':                 'Olá, como estás?',
  'Bonjour':             'Bonjour, comment allez-vous?',
  'Selamat pagi':        'Selamat pagi! Apa kabar hari ini?',
  'Bom dia':             'Bom dia! Tudo bem?',
  'Selamat sore':        'Selamat sore! Sudah pulang kerja?',
  'Boa tarde':           'Boa tarde! Tudo bem?',
  'Selamat malam':       'Selamat malam! Selamat beristirahat.',
  'Boa noite':           'Boa noite! Durma bem.',
  'Bonne nuit':          'Bonne nuit! Vous allez bien?',
  'Selamat tinggal':     'Selamat tinggal! Sampai jumpa lagi.',
  'Adeus':               'Adeus! Até breve.',
  'Au revoir':           'Au revoir! À bientôt.',
  'Terima kasih':        'Terima kasih atas bantuannya!',
  'Obrigado':            'Obrigado pela ajuda!',
  'Merci':               'Merci beaucoup pour votre aide!',
  'Maaf':                'Maaf, saya terlambat.',
  'Desculpe':            'Desculpe, pode repetir?',
  'Désolé':              'Désolé, je suis en retard.',
  'Saya tidak mengerti': 'Saya tidak mengerti. Bisa pelan-pelan?',
  'Não percebo':         'Não percebo. Pode falar mais devagar?',
  'Je ne comprends pas': 'Je ne comprends pas. Parlez lentement.',
  'Por favor':           'Por favor, fale mais devagar.',
  'Tolong':              'Tolong, di mana toilet?',
  "S'il vous plaît":     "S'il vous plaît, parlez lentement.",
  'Onde fica…?':         'Onde fica o correio?',
  'Di mana…?':           'Di mana kantor pos?',
  'Où est…?':            'Où est la poste ?',
  // Numbers
  'Satu':    'Saya punya satu kucing.',
  'Um':      'Tenho um irmão.',
  'Un':      "J'ai un frère.",
  'Dua':     'Ada dua apel di atas meja.',
  'Dois':    'Tenho dois gatos.',
  'Deux':    "J'ai deux sœurs.",
  'Tiga':    'Kami tinggal di tiga kamar.',
  'Três':    'Tenho três livros novos.',
  'Trois':   'Il y a trois chaises ici.',
  'Empat':   'Ada empat musim dalam setahun.',
  'Quatro':  'Temos quatro estações no ano.',
  'Quatre':  'Il y a quatre saisons.',
  'Lima':    'Saya beli lima buah jeruk.',
  'Cinco':   'Comprei cinco laranjas.',
  'Cinq':    "J'ai cinq livres.",
  'Enam':    'Ada enam telur di kulkas.',
  'Seis':    'Temos seis cadeiras na sala.',
  'Six':     'Il est six heures du soir.',
  'Tujuh':   'Seminggu ada tujuh hari.',
  'Sete':    'A semana tem sete dias.',
  'Sept':    'Une semaine a sept jours.',
  'Delapan': 'Toko buka pukul delapan pagi.',
  'Oito':    'O metro abre às oito da manhã.',
  'Huit':    'Le magasin ouvre à huit heures.',
  'Nol':          'Suhu malam ini hampir nol derajat.',
  'Zero':         'A temperatura desceu a zero graus esta noite.',
  'Sembilan':     'Ada sembilan planet di tata surya lama.',
  'Nove':         'Ela tem nove anos de idade.',
  'Sepuluh':      'Toko ini buka pukul sepuluh pagi.',
  'Dez':          'Ela tem dez dedos nas mãos.',
  'Sebelas':      'Rapat akan dimulai pukul sebelas.',
  'Onze':         'A reunião começa às onze horas.',
  'Tiga belas':   'Ada tiga belas siswa di dalam kelas.',
  'Treze':        'Há treze alunos na sala de aula.',
  'Delapan belas':'Dia baru berulang tahun ke delapan belas.',
  'Dezoito':      'Ele fez dezoito anos hoje.',
  'Dua puluh':    'Saya membeli dua puluh telur di pasar.',
  'Vinte':        'Comprei vinte laranjas no mercado.',
  // Family
  'Ayah':       'Ayah saya bekerja di Jakarta.',
  'Pai':        'O meu pai trabalha em Lisboa.',
  'Père':       'Mon père travaille à Paris.',
  'Ibu':        'Ibu saya seorang guru.',
  'Mãe':        'A minha mãe é professora.',
  'Mère':       'Ma mère est professeure.',
  'Kakak':      'Kakak saya tinggal di Bandung.',
  'Irmão':      'O meu irmão estuda medicina.',
  'Frère':      'Mon frère habite à Lyon.',
  'Adik':       'Adik saya masih sekolah.',
  'Kakek':      'Kakek saya suka berkebun.',
  'Avô':        'O meu avô tem oitenta anos.',
  'Grand-père': 'Mon grand-père a quatre-vingts ans.',
  'Nenek':      'Nenek saya pandai memasak.',
  'Avó':        'A minha avó faz bolos deliciosos.',
  'Grand-mère': 'Ma grand-mère fait de bons gâteaux.',
  'Suami':      'Suami saya seorang dokter.',
  'Marido':     'O meu marido é médico.',
  'Mari':       'Mon mari est médecin.',
  'Keluarga':   'Keluarga saya tinggal di Surabaya.',
  'Família':    'A minha família mora no Porto.',
  'Famille':    'Ma famille habite à Bordeaux.',
  // Colors
  'Merah':    'Apel berwarna merah.',
  'Vermelho': 'A maçã é vermelha.',
  'Biru':     'Langit hari ini sangat biru.',
  'Azul':     'O céu está muito azul hoje.',
  'Hijau':    'Pohon warnanya hijau.',
  'Verde':    'A árvore é verde.',
  'Kuning':   'Pisang matang berwarna kuning.',
  'Amarelo':  'O limão é de cor amarela.',
  'Oranye':   'Jeruk berwarna oranye.',
  'Laranja':  'A laranja tem cor de laranja.',
  'Putih':    'Seragam dokter berwarna putih.',
  'Branco':   'O jaleco do médico é branco.',
  'Hitam':    'Domba itu berbulu hitam.',
  'Preto':    'A ovelha tem lã preta.',
  'Coklat':   'Saya suka warna coklat.',
  'Castanho': 'Gosto da cor castanha.',
  'Rouge':    'La pomme est rouge.',
  'Bleu':     "Le ciel est bleu aujourd'hui.",
  'Vert':     "L'arbre est verte.",
  'Jaune':    'La banane mûre est jaune.',
  'Orange':   "L'orange est de couleur orange.",
  'Blanc':    'La blouse du médecin est blanche.',
  'Noir':     'Ce mouton a une laine noire.',
  'Marron':   'J’aime la couleur marron.',
  // Food & drink
  'Nasi':    'Saya selalu makan nasi untuk makan siang.',
  'Arroz':   'Como arroz com frango ao almoço.',
  'Riz':     'Je mange du riz avec du poulet.',
  'Ayam':    'Ayam goreng adalah makanan favorit saya.',
  'Frango':  'Gosto muito de frango grelhado.',
  'Poulet':  "J'aime le poulet rôti.",
  'Ikan':    'Ikan bakar sangat enak!',
  'Peixe':   'O peixe grelhado está delicioso.',
  'Poisson': 'Le poisson grillé est délicieux.',
  'Buah':    'Makan buah setiap hari itu sehat.',
  'Fruta':   'Como fruta fresca todos os dias.',
  'Fruit':   'Je mange des fruits frais chaque matin.',
  'Kopi':    'Saya minum kopi setiap pagi.',
  'Café': {
    'pt-PT': 'Tomo um café todas as manhãs.',
    'fr-FR': 'Je bois un café le matin.',
  },
  'Air':     'Minum banyak air putih itu baik untuk kesehatan.',
  'Água':    'Bebo muita água todos os dias.',
  'Eau':     "Je bois beaucoup d'eau.",
  'Roti':    'Saya makan roti untuk sarapan.',
  'Pão':     'Como pão com manteiga ao pequeno-almoço.',
  'Pain':    'Je mange du pain au petit-déjeuner.',
  'Telur':   'Saya suka telur rebus untuk sarapan.',
  'Ovo':     'Como ovos mexidos ao pequeno-almoço.',
  'Carne':   'Gosto de carne assada com batatas.',
  'Viande':  'Je mange de la viande grillée ce soir.',
  // Family (additions)
  'Filho':   'O meu filho tem cinco anos de idade.',
  'Fils':    'Mon fils a cinq ans.',
  // Body
  'Cabeça':   'A minha cabeça dói um pouco hoje.',
  'Nariz':    'O nariz serve para respirar e cheirar.',
  'Boca':     'Abrimos a boca para comer e falar.',
  'Orelha':   'As minhas orelhas ficam frias no inverno.',
  'Cabelo':   'Ela tem cabelo comprido e muito bonito.',
  'Kepala':   'Kepala saya sakit setelah belajar lama.',
  'Hidung':   'Hidung saya meler karena masuk angin.',
  'Mulut':    'Buka mulut Anda dan katakan "ah".',
  'Telinga':  'Telinga saya sakit karena cuaca dingin.',
  'Rambut':   'Rambut saya hitam dan lurus.',
  'Tête':     "J'ai mal à la tête ce matin.",
  'Nez':      'Le nez sert à respirer et à sentir.',
  'Bouche':   "Ouvrez la bouche, s'il vous plaît.",
  'Oreille':  "J'ai mal à l'oreille depuis hier.",
  'Cheveux':  'Elle a les cheveux longs et bruns.',
  // Verbs
  'comer':      'Vou comer pizza ao jantar hoje.',
  'beber':      'Bebo dois litros de água por dia.',
  'estudar':    'Preciso de estudar para o exame amanhã.',
  'trabalhar':  'Ele trabalha numa empresa de tecnologia.',
  'brincar':    'As crianças brincam no jardim após a escola.',
  'ler':        'Gosto de ler livros antes de dormir.',
  'escrever':   'Ele escreve cartas para a família.',
  'comprar':    'Vou ao mercado comprar fruta fresca.',
  'ir':         'Vou ao supermercado depois do trabalho.',
  'morar':      'Moro em Lisboa há cinco anos.',
  'makan':      'Saya makan nasi goreng setiap pagi.',
  'minum':      'Saya minum dua liter air setiap hari.',
  'belajar':    'Saya belajar bahasa Portugis di sekolah.',
  'bekerja':    'Ayah saya bekerja di perusahaan besar.',
  'bermain':    'Anak-anak bermain bola di taman.',
  'membaca':    'Saya suka membaca buku sebelum tidur.',
  'menulis':    'Dia menulis surat untuk keluarganya.',
  'membeli':    'Kami pergi ke pasar untuk membeli sayuran.',
  'pergi':      'Saya pergi ke sekolah setiap pagi.',
  'tinggal':    'Saya tinggal di Jakarta bersama keluarga.',
  'datang':     'Dia datang ke pesta tepat waktu.',
  'manger':     'Je mange une pomme chaque matin.',
  'boire':      'Je bois du café avant de travailler.',
  'étudier':    "J'étudie le français à l'université.",
  'travailler': 'Je travaille dans un grand bureau.',
  'jouer':      'Les enfants jouent dans le parc.',
  'lire':       "J'aime lire des livres le soir.",
  'écrire':     'Il écrit une lettre à ses parents.',
  'acheter':    'Je vais au marché acheter des légumes.',
  'aller':      "Je vais à l'école tous les matins.",
  'habiter':    "J'habite à Paris depuis trois ans.",
  'venir':      'Il vient chez moi ce soir.',
  // Places
  'mercado':      'Vou ao mercado todas as manhãs comprar legumes.',
  'escola':       'A minha filha vai à escola de manhã.',
  'escritório':   'O meu pai trabalha no escritório.',
  'parque':       'Passeio no parque todos os fins de semana.',
  'restaurante':  'Fomos a um restaurante italiano ontem à noite.',
  'casa':         'Fico em casa quando o tempo está mau.',
  'hospital':     'O médico trabalha no hospital central.',
  'farmácia':     'Comprei medicamentos na farmácia.',
  'aeroporto':    'Fui ao aeroporto buscar a minha mãe.',
  'biblioteca':   'Estudo na biblioteca todas as tardes.',
  'teatro':       'Fomos ver uma peça de teatro ao sábado.',
  'igreja':       'A família vai à igreja ao domingo.',
  'pasar':        'Ibu saya pergi ke pasar setiap pagi.',
  'sekolah':      'Saya pergi ke sekolah setiap hari.',
  'kantor':       'Ayah saya bekerja di kantor pusat.',
  'taman':        'Saya suka berjalan-jalan di taman kota.',
  'restoran':     'Kami makan malam di restoran mewah.',
  'rumah':        'Saya tinggal di rumah yang nyaman.',
  'rumah sakit':  'Dokter itu bekerja di rumah sakit.',
  'apotek':       'Saya membeli obat di apotek dekat rumah.',
  'bandara':      'Kami tiba di bandara pukul delapan pagi.',
  'perpustakaan': 'Saya belajar di perpustakaan setiap sore.',
  'teater':       'Kami menonton pertunjukan di teater malam ini.',
  'gereja':       'Keluarga kami pergi ke gereja setiap minggu.',
  'marché':       'Ma mère va au marché chaque matin.',
  'école':        "Mon fils va à l'école le matin.",
  'bureau':       'Mon père travaille dans un grand bureau.',
  'parc':         'Je me promène dans le parc le week-end.',
  'restaurant':   'Nous avons dîné dans un beau restaurant.',
  'maison':       'Je reste à la maison quand il pleut.',
  'hôpital':      "Le médecin travaille à l'hôpital.",
  'pharmacie':    "J'ai acheté des médicaments à la pharmacie.",
  'aéroport':     "Je suis allé à l'aéroport chercher ma mère.",
  'bibliothèque': "J'étudie à la bibliothèque tous les après-midi.",
  'théâtre':      'Nous avons vu une pièce de théâtre samedi.',
  'église':       "Ma famille va à l'église le dimanche.",
  // Questions
  'quem':              'Quem é o teu amigo?',
  'o que':             'O que vais comer?',
  'quando':            'Quando vais a Lisboa?',
  'como':              'Como estás?',
  'porquê':           'Porquê esta loja está fechada?',
  'quanto':            'Quanto custa esta camisa?',
  'qual':              'Qual é o teu carro?',
  'para onde':         'Para onde vais?',
  'de onde':           'De onde és?',
  'a que horas':       'A que horas almoçamos?',
  'quanto tempo':      'Quanto tempo dura esta aula?',
  'siapa':             'Siapa nama temanmu?',
  'apa':               'Apa makanan favoritmu?',
  'kapan':             'Kapan kamu pergi ke Jakarta?',
  'bagaimana':         'Bagaimana kabarmu?',
  'mengapa':           'Mengapa toko ini tutup?',
  'berapa':            'Berapa harga kemeja ini?',
  'yang mana':         'Yang mana mobilmu?',
  'ke mana':           'Ke mana kamu pergi?',
  'dari mana':         'Dari mana kamu berasal?',
  'jam berapa':        'Jam berapa kita makan siang?',
  'berapa lama':       'Berapa lama kelas ini?',
  'qui':               'Qui est ton ami ?',
  'quoi':              "C'est quoi, ton plat préféré ?",
  'quand':             'Quand vas-tu à Paris ?',
  'comment':           'Comment vas-tu ?',
  'pourquoi':          'Pourquoi ce magasin est-il fermé ?',
  'combien':           'Combien coûte cette chemise ?',
  'lequel':            'Lequel est ta voiture ?',
  'vers où':           'Vers où tu vas ?',
  "d'où":              "D'où viens-tu ?",
  'à quelle heure':    'À quelle heure on déjeune ?',
  'combien de temps':  'Combien de temps dure ce cours ?',
};

// ── Resources ──────────────────────────────────────────────
// Reference material compiled from uploaded PDFs.
// Each entry: { id, icon, title, source, sections[] }
// Section: { heading, rows?[][], cols?[], notes?[] }

const RESOURCES = {

  // ── Portuguese ─────────────────────────────
  'pt-PT': [
    {
      id: 'pt-vocab',
      icon: '📖',
      title: 'Vocabulário Essencial',
      source: 'Basic Portuguese Grammar · Dicionário',
      sections: [
        {
          heading: 'Família / Family',
          cols: ['Português', 'English', 'Bahasa Indonesia'],
          rows: [
            ['pai',       'father',       'ayah'],
            ['mãe',       'mother',       'ibu'],
            ['irmão',     'brother',      'kakak laki-laki'],
            ['irmã',      'sister',       'kakak perempuan'],
            ['avô',       'grandfather',  'kakek'],
            ['avó',       'grandmother',  'nenek'],
            ['filho',     'son',          'anak laki-laki'],
            ['filha',     'daughter',     'anak perempuan'],
            ['marido',    'husband',      'suami'],
            ['esposa',    'wife',         'istri'],
          ],
        },
        {
          heading: 'O Corpo / Body',
          cols: ['Português', 'English', 'Bahasa Indonesia'],
          rows: [
            ['cabeça',   'head',    'kepala'],
            ['olho',     'eye',     'mata'],
            ['nariz',    'nose',    'hidung'],
            ['boca',     'mouth',   'mulut'],
            ['orelha',   'ear',     'telinga'],
            ['mão',      'hand',    'tangan'],
            ['braço',    'arm',     'lengan'],
            ['perna',    'leg',     'kaki'],
            ['cabelo',   'hair',    'rambut'],
            ['coração',  'heart',   'jantung'],
          ],
        },
        {
          heading: 'Comida / Food',
          cols: ['Português', 'English', 'Bahasa Indonesia'],
          rows: [
            ['pão',    'bread',   'roti'],
            ['leite',  'milk',    'susu'],
            ['água',   'water',   'air'],
            ['café',   'coffee',  'kopi'],
            ['fruta',  'fruit',   'buah'],
            ['carne',  'meat',    'daging'],
            ['peixe',  'fish',    'ikan'],
            ['arroz',  'rice',    'nasi'],
            ['queijo', 'cheese',  'keju'],
            ['ovo',    'egg',     'telur'],
          ],
        },
        {
          heading: 'Cores / Colours',
          cols: ['Português', 'English', 'Bahasa Indonesia'],
          rows: [
            ['vermelho', 'red',    'merah'],
            ['azul',     'blue',   'biru'],
            ['verde',    'green',  'hijau'],
            ['amarelo',  'yellow', 'kuning'],
            ['branco',   'white',  'putih'],
            ['preto',    'black',  'hitam'],
            ['castanho', 'brown',  'coklat'],
            ['laranja',  'orange', 'oranye'],
            ['cinzento', 'grey',   'abu-abu'],
            ['rosa',     'pink',   'merah muda'],
          ],
        },
      ],
    },
    {
      id: 'pt-grammar',
      icon: '📝',
      title: 'Gramática Básica',
      source: 'Basic Portuguese Grammar',
      sections: [
        {
          heading: 'Artigos / Articles',
          notes: [
            'Definido: o (m. sing.) · a (f. sing.) · os (m. pl.) · as (f. pl.)',
            'Indefinido: um (m. sing.) · uma (f. sing.) · uns (m. pl.) · umas (f. pl.)',
            'Ex: o pai, a mãe, os filhos, as filhas',
          ],
        },
        {
          heading: 'Pronomes / Pronouns',
          cols: ['Português', 'English'],
          rows: [
            ['eu',          'I'],
            ['tu / você',   'you'],
            ['ele / ela',   'he / she'],
            ['nós',         'we'],
            ['vocês',       'you (pl.)'],
            ['eles / elas', 'they'],
          ],
        },
        {
          heading: 'Ser vs Estar',
          notes: [
            'SER — identidade/origem: Eu sou português. (I am Portuguese.)',
            'ESTAR — estado temporário: Eu estou bem. (I am well.)',
            'SER: sou · és · é · somos · são',
            'ESTAR: estou · estás · está · estamos · estão',
          ],
        },
        {
          heading: 'Números / Numbers',
          cols: ['#', 'Português', 'English'],
          rows: [
            ['1', 'um / uma', 'one'],
            ['2', 'dois / duas', 'two'],
            ['3', 'três', 'three'],
            ['4', 'quatro', 'four'],
            ['5', 'cinco', 'five'],
            ['6', 'seis', 'six'],
            ['7', 'sete', 'seven'],
            ['8', 'oito', 'eight'],
            ['9', 'nove', 'nine'],
            ['10', 'dez', 'ten'],
          ],
        },
      ],
    },
  ],

  // ── Indonesian ────────────────────────────────────────
  'id-ID': [
    {
      id: 'id-vocab',
      icon: '📖',
      title: 'Kosakata Esensial',
      source: 'Buku Bahasa Indonesia 1 · BIPA A1',
      sections: [
        {
          heading: 'Salam / Greetings',
          cols: ['Bahasa Indonesia', 'English', 'Português'],
          rows: [
            ['selamat pagi',    'good morning',         'bom dia'],
            ['selamat siang',   'good midday',          'boa tarde (meio-dia)'],
            ['selamat sore',    'good afternoon',       'boa tarde'],
            ['selamat malam',   'good evening',         'boa noite'],
            ['selamat tinggal', 'goodbye',              'adeus'],
            ['terima kasih',    'thank you',            'obrigado/a'],
            ['sama-sama',       "you're welcome",       'de nada'],
            ['tolong',          'please / help',        'por favor'],
            ['maaf',            'sorry',                'desculpe'],
            ['permisi',         'excuse me',            'com licença'],
          ],
        },
        {
          heading: 'Keluarga / Family',
          cols: ['Bahasa Indonesia', 'English', 'Português'],
          rows: [
            ['ayah / bapak',        'father',           'pai'],
            ['ibu',                 'mother',           'mãe'],
            ['kakak laki-laki',     'older brother',    'irmão mais velho'],
            ['kakak perempuan',     'older sister',     'irmã mais velha'],
            ['adik',                'younger sibling',  'irmão/irmã mais novo/a'],
            ['kakek',               'grandfather',      'avô'],
            ['nenek',               'grandmother',      'avó'],
            ['suami',               'husband',          'marido'],
            ['istri',               'wife',             'esposa'],
            ['keluarga',            'family',           'família'],
          ],
        },
        {
          heading: 'Warna / Colours',
          cols: ['Bahasa Indonesia', 'English', 'Português'],
          rows: [
            ['merah',      'red',    'vermelho'],
            ['biru',       'blue',   'azul'],
            ['hijau',      'green',  'verde'],
            ['kuning',     'yellow', 'amarelo'],
            ['putih',      'white',  'branco'],
            ['hitam',      'black',  'preto'],
            ['coklat',     'brown',  'castanho'],
            ['oranye',     'orange', 'laranja'],
            ['abu-abu',    'grey',   'cinzento'],
            ['merah muda', 'pink',   'rosa'],
          ],
        },
        {
          heading: 'Makanan / Food',
          cols: ['Bahasa Indonesia', 'English', 'Português'],
          rows: [
            ['nasi',   'rice',       'arroz'],
            ['ayam',   'chicken',    'frango'],
            ['ikan',   'fish',       'peixe'],
            ['sayur',  'vegetables', 'legumes'],
            ['buah',   'fruit',      'fruta'],
            ['roti',   'bread',      'pão'],
            ['telur',  'egg',        'ovo'],
            ['susu',   'milk',       'leite'],
            ['kopi',   'coffee',     'café'],
            ['air',    'water',      'água'],
          ],
        },
      ],
    },
    {
      id: 'id-grammar',
      icon: '📝',
      title: 'Tata Bahasa Dasar',
      source: 'Buku Bahasa Indonesia 1',
      sections: [
        {
          heading: 'Kata Ganti / Pronouns',
          cols: ['Bahasa Indonesia', 'English', 'Português'],
          rows: [
            ['saya / aku',  'I',             'eu'],
            ['kamu / Anda', 'you',           'tu / você'],
            ['dia / ia',    'he / she',      'ele / ela'],
            ['kami',        'we (excl.)',     'nós (excl.)'],
            ['kita',        'we (incl.)',     'nós (incl.)'],
            ['mereka',      'they',          'eles / elas'],
          ],
        },
        {
          heading: 'Negasi / Negation',
          notes: [
            'TIDAK — negates verbs & adjectives: Saya tidak makan. (I don\'t eat.)',
            'BUKAN — negates nouns: Ini bukan nasi. (This is not rice.)',
            'BELUM — not yet: Saya belum makan. (I haven\'t eaten yet.)',
          ],
        },
        {
          heading: 'Waktu / Time',
          cols: ['Bahasa Indonesia', 'English', 'Português'],
          rows: [
            ['pagi',     'morning',   'manhã'],
            ['siang',    'midday',    'meio-dia'],
            ['sore',     'afternoon', 'tarde'],
            ['malam',    'night',     'noite'],
            ['hari ini', 'today',     'hoje'],
            ['besok',    'tomorrow',  'amanhã'],
            ['kemarin',  'yesterday', 'ontem'],
          ],
        },
        {
          heading: 'Angka / Numbers',
          cols: ['#', 'Bahasa Indonesia', 'English'],
          rows: [
            ['1',  'satu',    'one'],
            ['2',  'dua',     'two'],
            ['3',  'tiga',    'three'],
            ['4',  'empat',   'four'],
            ['5',  'lima',    'five'],
            ['6',  'enam',    'six'],
            ['7',  'tujuh',   'seven'],
            ['8',  'delapan', 'eight'],
            ['9',  'sembilan','nine'],
            ['10', 'sepuluh', 'ten'],
          ],
        },
      ],
    },
  ],

  // ── French ────────────────────────────────────────────
  'fr-FR': [
    {
      id: 'fr-vocab',
      icon: '📖',
      title: 'Vocabulaire Essentiel',
      source: 'Dictionnaire visuel · French Basics Grammar',
      sections: [
        {
          heading: 'Famille / Family',
          cols: ['Français', 'English', 'Português'],
          rows: [
            ['père',       'father',      'pai'],
            ['mère',       'mother',      'mãe'],
            ['frère',      'brother',     'irmão'],
            ['sœur',       'sister',      'irmã'],
            ['grand-père', 'grandfather', 'avô'],
            ['grand-mère', 'grandmother', 'avó'],
            ['fils',       'son',         'filho'],
            ['fille',      'daughter',    'filha'],
            ['mari',       'husband',     'marido'],
            ['femme',      'wife',        'esposa'],
          ],
        },
        {
          heading: 'Le Corps / Body',
          cols: ['Français', 'English', 'Português'],
          rows: [
            ['tête',         'head',  'cabeça'],
            ['œil / yeux',   'eye / eyes', 'olho / olhos'],
            ['nez',          'nose',  'nariz'],
            ['bouche',       'mouth', 'boca'],
            ['oreille',      'ear',   'orelha'],
            ['main',         'hand',  'mão'],
            ['bras',         'arm',   'braço'],
            ['jambe',        'leg',   'perna'],
            ['cheveux',      'hair',  'cabelo'],
            ['cœur',         'heart', 'coração'],
          ],
        },
        {
          heading: 'Nourriture / Food',
          cols: ['Français', 'English', 'Português'],
          rows: [
            ['pain',    'bread',  'pão'],
            ['lait',    'milk',   'leite'],
            ['eau',     'water',  'água'],
            ['café',    'coffee', 'café'],
            ['fruit',   'fruit',  'fruta'],
            ['viande',  'meat',   'carne'],
            ['poisson', 'fish',   'peixe'],
            ['riz',     'rice',   'arroz'],
            ['fromage', 'cheese', 'queijo'],
            ['œuf',     'egg',    'ovo'],
          ],
        },
        {
          heading: 'Couleurs / Colours',
          cols: ['Français', 'English', 'Português'],
          rows: [
            ['rouge',          'red',    'vermelho'],
            ['bleu(e)',         'blue',   'azul'],
            ['vert(e)',         'green',  'verde'],
            ['jaune',          'yellow', 'amarelo'],
            ['blanc / blanche','white',  'branco'],
            ['noir(e)',         'black',  'preto'],
            ['marron',         'brown',  'castanho'],
            ['orange',         'orange', 'laranja'],
          ],
        },
      ],
    },
    {
      id: 'fr-grammar',
      icon: '📝',
      title: 'Grammaire de Base',
      source: 'French Basics Grammar Book',
      sections: [
        {
          heading: 'Articles',
          notes: [
            'Défini: le (m. sing.) · la (f. sing.) · les (pl.)',
            'Indéfini: un (m. sing.) · une (f. sing.) · des (pl.)',
            'Ex: le père, la mère, les enfants, un ami, une amie',
          ],
        },
        {
          heading: 'Pronoms / Pronouns',
          cols: ['Français', 'English', 'Português'],
          rows: [
            ['je',           'I',              'eu'],
            ['tu',           'you (informal)', 'tu'],
            ['vous',         'you (formal/pl.)','você / vocês'],
            ['il / elle',    'he / she',       'ele / ela'],
            ['nous',         'we',             'nós'],
            ['ils / elles',  'they',           'eles / elas'],
          ],
        },
        {
          heading: 'Être (to be)',
          notes: [
            'je suis · tu es · il/elle est',
            'nous sommes · vous êtes · ils/elles sont',
            'Ex: Je suis étudiant(e). (I am a student.)',
          ],
        },
        {
          heading: 'Nombres / Numbers',
          cols: ['#', 'Français', 'English'],
          rows: [
            ['1',  'un / une', 'one'],
            ['2',  'deux',     'two'],
            ['3',  'trois',    'three'],
            ['4',  'quatre',   'four'],
            ['5',  'cinq',     'five'],
            ['6',  'six',      'six'],
            ['7',  'sept',     'seven'],
            ['8',  'huit',     'eight'],
            ['9',  'neuf',     'nine'],
            ['10', 'dix',      'ten'],
          ],
        },
      ],
    },
  ],
};
